/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcGeneric"
 * 	found in "ISO_TS_14906_Generic.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Attributes_H_
#define	_Attributes_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _Attributes_H_ */
#include <asn_internal.h>
