/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DayOfWeek_H_
#define	_DayOfWeek_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DayOfWeek {
	DayOfWeek_unused	= 0,
	DayOfWeek_monday	= 1,
	DayOfWeek_tuesday	= 2,
	DayOfWeek_wednesday	= 3,
	DayOfWeek_thursday	= 4,
	DayOfWeek_friday	= 5,
	DayOfWeek_saturday	= 6,
	DayOfWeek_sunday	= 7
} e_DayOfWeek;

/* DayOfWeek */
typedef BIT_STRING_t	 DayOfWeek_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DayOfWeek;
asn_struct_free_f DayOfWeek_free;
asn_struct_print_f DayOfWeek_print;
asn_constr_check_f DayOfWeek_constraint;
ber_type_decoder_f DayOfWeek_decode_ber;
der_type_encoder_f DayOfWeek_encode_der;
xer_type_decoder_f DayOfWeek_decode_xer;
xer_type_encoder_f DayOfWeek_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DayOfWeek_H_ */
#include <asn_internal.h>
