/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DrivenLineOffsetSm_H_
#define	_DrivenLineOffsetSm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DrivenLineOffsetSm */
typedef long	 DrivenLineOffsetSm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DrivenLineOffsetSm;
asn_struct_free_f DrivenLineOffsetSm_free;
asn_struct_print_f DrivenLineOffsetSm_print;
asn_constr_check_f DrivenLineOffsetSm_constraint;
ber_type_decoder_f DrivenLineOffsetSm_decode_ber;
der_type_encoder_f DrivenLineOffsetSm_encode_der;
xer_type_decoder_f DrivenLineOffsetSm_decode_xer;
xer_type_encoder_f DrivenLineOffsetSm_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DrivenLineOffsetSm_H_ */
#include <asn_internal.h>
