/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicRegistrationIdentificationVehicleDataModule"
 * 	found in "ISO_TS_24534-3.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EuVehicleCategoryM_H_
#define	_EuVehicleCategoryM_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuVehicleCategoryM {
	EuVehicleCategoryM_m1	= 0,
	EuVehicleCategoryM_m2	= 1,
	EuVehicleCategoryM_m3	= 2
} e_EuVehicleCategoryM;

/* EuVehicleCategoryM */
typedef long	 EuVehicleCategoryM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuVehicleCategoryM;
asn_struct_free_f EuVehicleCategoryM_free;
asn_struct_print_f EuVehicleCategoryM_print;
asn_constr_check_f EuVehicleCategoryM_constraint;
ber_type_decoder_f EuVehicleCategoryM_decode_ber;
der_type_encoder_f EuVehicleCategoryM_encode_der;
xer_type_decoder_f EuVehicleCategoryM_decode_xer;
xer_type_encoder_f EuVehicleCategoryM_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EuVehicleCategoryM_H_ */
#include <asn_internal.h>
