/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "ISO_TS_14906_Application.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Int1_H_
#define	_Int1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Int1 */
typedef long	 Int1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Int1;
asn_struct_free_f Int1_free;
asn_struct_print_f Int1_print;
asn_constr_check_f Int1_constraint;
ber_type_decoder_f Int1_decode_ber;
der_type_encoder_f Int1_encode_der;
xer_type_decoder_f Int1_decode_xer;
xer_type_encoder_f Int1_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Int1_H_ */
#include <asn_internal.h>
