/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "ISO_TS_14906_Application.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Int2_H_
#define	_Int2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Int2 */
typedef long	 Int2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Int2;
asn_struct_free_f Int2_free;
asn_struct_print_f Int2_print;
asn_constr_check_f Int2_constraint;
ber_type_decoder_f Int2_decode_ber;
der_type_encoder_f Int2_encode_der;
xer_type_decoder_f Int2_decode_xer;
xer_type_encoder_f Int2_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Int2_H_ */
#include <asn_internal.h>
