/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IviIdentificationNumber_H_
#define	_IviIdentificationNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IviIdentificationNumber */
typedef long	 IviIdentificationNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IviIdentificationNumber;
asn_struct_free_f IviIdentificationNumber_free;
asn_struct_print_f IviIdentificationNumber_print;
asn_constr_check_f IviIdentificationNumber_constraint;
ber_type_decoder_f IviIdentificationNumber_decode_ber;
der_type_encoder_f IviIdentificationNumber_encode_der;
xer_type_decoder_f IviIdentificationNumber_decode_xer;
xer_type_encoder_f IviIdentificationNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IviIdentificationNumber_H_ */
#include <asn_internal.h>
