/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IVILaneWidth_H_
#define	_IVILaneWidth_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IVILaneWidth */
typedef long	 IVILaneWidth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IVILaneWidth;
asn_struct_free_f IVILaneWidth_free;
asn_struct_print_f IVILaneWidth_print;
asn_constr_check_f IVILaneWidth_constraint;
ber_type_decoder_f IVILaneWidth_decode_ber;
der_type_encoder_f IVILaneWidth_encode_der;
xer_type_decoder_f IVILaneWidth_decode_xer;
xer_type_encoder_f IVILaneWidth_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IVILaneWidth_H_ */
#include <asn_internal.h>
