/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RegionalExtension_H_
#define	_RegionalExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RegionId.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RegionalExtension */
typedef struct RegionalExtension_272P0 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P0_t;
typedef struct RegionalExtension_272P1 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P1_t;
typedef struct RegionalExtension_272P2 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P2_t;
typedef struct RegionalExtension_272P3 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P3_t;
typedef struct RegionalExtension_272P4 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P4_t;
typedef struct RegionalExtension_272P5 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P5_t;
typedef struct RegionalExtension_272P6 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P6_t;
typedef struct RegionalExtension_272P7 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P7_t;
typedef struct RegionalExtension_272P8 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P8_t;
typedef struct RegionalExtension_272P9 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P9_t;
typedef struct RegionalExtension_272P10 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P10_t;
typedef struct RegionalExtension_272P11 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P11_t;
typedef struct RegionalExtension_272P12 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P12_t;
typedef struct RegionalExtension_272P13 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P13_t;
typedef struct RegionalExtension_272P14 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P14_t;
typedef struct RegionalExtension_272P15 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P15_t;
typedef struct RegionalExtension_272P16 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P16_t;
typedef struct RegionalExtension_272P17 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P17_t;
typedef struct RegionalExtension_272P18 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P18_t;
typedef struct RegionalExtension_272P19 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P19_t;
typedef struct RegionalExtension_272P20 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P20_t;
typedef struct RegionalExtension_272P21 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P21_t;
typedef struct RegionalExtension_272P22 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P22_t;
typedef struct RegionalExtension_272P23 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P23_t;
typedef struct RegionalExtension_272P24 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P24_t;
typedef struct RegionalExtension_272P25 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_272P25_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P0;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P1;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P2;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P3;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P4;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P5;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P6;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P7;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P8;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P9;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P10;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P11;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P12;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P13;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P14;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P15;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P16;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P17;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P18;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P19;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P20;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P21;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P22;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P23;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P24;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_272P25;

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalExtension_H_ */
#include <asn_internal.h>
