/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RequestorPositionVector_H_
#define	_RequestorPositionVector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Position3D.h"
#include "Angle.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TransmissionAndSpeed;

/* RequestorPositionVector */
typedef struct RequestorPositionVector {
	Position3D_t	 position;
	Angle_t	*heading	/* OPTIONAL */;
	struct TransmissionAndSpeed	*speed	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestorPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestorPositionVector;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TransmissionAndSpeed.h"

#endif	/* _RequestorPositionVector_H_ */
#include <asn_internal.h>
