/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RoadwayCrownAngle_H_
#define	_RoadwayCrownAngle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadwayCrownAngle */
typedef long	 RoadwayCrownAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadwayCrownAngle;
asn_struct_free_f RoadwayCrownAngle_free;
asn_struct_print_f RoadwayCrownAngle_print;
asn_constr_check_f RoadwayCrownAngle_constraint;
ber_type_decoder_f RoadwayCrownAngle_decode_ber;
der_type_encoder_f RoadwayCrownAngle_encode_der;
xer_type_decoder_f RoadwayCrownAngle_decode_xer;
xer_type_encoder_f RoadwayCrownAngle_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadwayCrownAngle_H_ */
#include <asn_internal.h>
