/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ROI_H_
#define	_ROI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ROI */
typedef long	 ROI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ROI;
asn_struct_free_f ROI_free;
asn_struct_print_f ROI_print;
asn_constr_check_f ROI_constraint;
ber_type_decoder_f ROI_decode_ber;
der_type_encoder_f ROI_encode_der;
xer_type_decoder_f ROI_decode_xer;
xer_type_encoder_f ROI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ROI_H_ */
#include <asn_internal.h>
