/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Segment_H_
#define	_Segment_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PolygonalLine.h"
#include "IVILaneWidth.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Segment */
typedef struct Segment {
	PolygonalLine_t	 line;
	IVILaneWidth_t	*laneWidth	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Segment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Segment;

#ifdef __cplusplus
}
#endif

#endif	/* _Segment_H_ */
#include <asn_internal.h>
