/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "LibIts-ITS-Container-r1318.asn"
 */

#ifndef	_SteeringWheelAngleConfidence_H_
#define	_SteeringWheelAngleConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SteeringWheelAngleConfidence {
	SteeringWheelAngleConfidence_equalOrWithinOnePointFiveDegree	= 1,
	SteeringWheelAngleConfidence_outOfRange	= 126,
	SteeringWheelAngleConfidence_unavailable	= 127
} e_SteeringWheelAngleConfidence;

/* SteeringWheelAngleConfidence */
typedef long	 SteeringWheelAngleConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SteeringWheelAngleConfidence;
asn_struct_free_f SteeringWheelAngleConfidence_free;
asn_struct_print_f SteeringWheelAngleConfidence_print;
asn_constr_check_f SteeringWheelAngleConfidence_constraint;
ber_type_decoder_f SteeringWheelAngleConfidence_decode_ber;
der_type_encoder_f SteeringWheelAngleConfidence_encode_der;
xer_type_decoder_f SteeringWheelAngleConfidence_decode_xer;
xer_type_encoder_f SteeringWheelAngleConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SteeringWheelAngleConfidence_H_ */
#include <asn_internal.h>
