/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TimeReference_H_
#define	_TimeReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeReference {
	TimeReference_oneMilliSec	= 1
} e_TimeReference;

/* TimeReference */
typedef long	 TimeReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeReference;
asn_struct_free_f TimeReference_free;
asn_struct_print_f TimeReference_print;
asn_constr_check_f TimeReference_constraint;
ber_type_decoder_f TimeReference_decode_ber;
der_type_encoder_f TimeReference_encode_der;
xer_type_decoder_f TimeReference_decode_xer;
xer_type_encoder_f TimeReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeReference_H_ */
#include <asn_internal.h>
