/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "ISO_TS_19091.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TimeIntervalConfidence_H_
#define	_TimeIntervalConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeIntervalConfidence */
typedef long	 TimeIntervalConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeIntervalConfidence;
asn_struct_free_f TimeIntervalConfidence_free;
asn_struct_print_f TimeIntervalConfidence_print;
asn_constr_check_f TimeIntervalConfidence_constraint;
ber_type_decoder_f TimeIntervalConfidence_decode_ber;
der_type_encoder_f TimeIntervalConfidence_encode_der;
xer_type_decoder_f TimeIntervalConfidence_decode_xer;
xer_type_encoder_f TimeIntervalConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeIntervalConfidence_H_ */
#include <asn_internal.h>
