/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "ISO_TS_14906_Application.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_UnitType_H_
#define	_UnitType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnitType {
	UnitType_mg_km	= 0,
	UnitType_mg_kWh	= 1
} e_UnitType;

/* UnitType */
typedef long	 UnitType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnitType;
asn_struct_free_f UnitType_free;
asn_struct_print_f UnitType_print;
asn_constr_check_f UnitType_constraint;
ber_type_decoder_f UnitType_decode_ber;
der_type_encoder_f UnitType_encode_der;
xer_type_decoder_f UnitType_decode_xer;
xer_type_encoder_f UnitType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnitType_H_ */
#include <asn_internal.h>
