/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VcOption_H_
#define	_VcOption_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VcOption {
	VcOption_none	= 0,
	VcOption_a	= 1,
	VcOption_b	= 2,
	VcOption_c	= 3,
	VcOption_d	= 4,
	VcOption_e	= 5,
	VcOption_f	= 6,
	VcOption_g	= 7
} e_VcOption;

/* VcOption */
typedef long	 VcOption_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VcOption;
asn_struct_free_f VcOption_free;
asn_struct_print_f VcOption_print;
asn_constr_check_f VcOption_constraint;
ber_type_decoder_f VcOption_decode_ber;
der_type_encoder_f VcOption_encode_der;
xer_type_decoder_f VcOption_decode_xer;
xer_type_encoder_f VcOption_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VcOption_H_ */
#include <asn_internal.h>
