/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VED_H_
#define	_VED_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Distance;
struct Weight;

/* VED */
typedef struct VED {
	struct Distance	*hei	/* OPTIONAL */;
	struct Distance	*wid	/* OPTIONAL */;
	struct Distance	*vln	/* OPTIONAL */;
	struct Weight	*wei	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VED_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VED;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Distance.h"
#include "Weight.h"

#endif	/* _VED_H_ */
#include <asn_internal.h>
