/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "ISO_TS_19321.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Zid_H_
#define	_Zid_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Zid */
typedef long	 Zid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Zid;
asn_struct_free_f Zid_free;
asn_struct_print_f Zid_print;
asn_constr_check_f Zid_constraint;
ber_type_decoder_f Zid_decode_ber;
der_type_encoder_f Zid_encode_der;
xer_type_decoder_f Zid_decode_xer;
xer_type_encoder_f Zid_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Zid_H_ */
#include <asn_internal.h>
